# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 4, 21, 2, 43, 780011)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(choices=[(b'activate', b'Activate'), (b'activating', b'Activating'), (b'active', b'Active'), (b'delete', b'Delete'), (b'deleting', b'Deleting'), (b'deleted', b'Deleted'), (b'pending', b'Pending'), (b'failed', b'Failed'), (b'disuser', b'Disuser')], max_length=16),
        ),
    ]
